# Generated by Django 4.0.4 on 2022-06-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_post_timestamp_alter_user_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='seed',
            field=models.CharField(default='F+0%$\\Y(Ld', max_length=10),
        ),
    ]
