# Generated by Django 4.0.4 on 2022-06-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_user_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='seed',
            field=models.CharField(default='MM4+vu~j=B', max_length=10),
        ),
    ]
