# Generated by Django 4.0.4 on 2022-06-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_alter_user_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='seed',
            field=models.CharField(default='rELNwqjjXG', max_length=10),
        ),
    ]
