# Generated by Django 4.0.4 on 2022-07-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsArchive', '0003_alter_article_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='viewed_by',
            new_name='viewers',
        ),
        migrations.AlterField(
            model_name='configuration',
            name='searchIn',
            field=models.TextField(blank=True, default='_empty_--'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sources',
            field=models.TextField(blank=True, default='_empty_--'),
        ),
    ]
