# Generated by Django 4.0.4 on 2022-07-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsArchive', '0005_alter_article_publishedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='config_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publishedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
