# Generated by Django 4.0.4 on 2022-07-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsArchive', '0006_configuration_config_date_alter_article_publishedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=4),
        ),
    ]
