# Generated by Django 4.0.4 on 2022-07-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsArchive', '0007_alter_configuration_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=10),
        ),
    ]
