# Generated by Django 4.0.4 on 2022-07-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsArchive', '0008_alter_configuration_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='catagory',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='country',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='queryString',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='searchIn',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sources',
            field=models.TextField(blank=True),
        ),
    ]
