# Generated by Django 4.0.4 on 2022-07-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsArchive', '0009_alter_article_author_alter_article_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='info',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
