# Generated by Django 4.0.4 on 2022-07-09 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NewsArchive', '0010_configuration_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='viewers',
        ),
        migrations.AddField(
            model_name='article',
            name='viewer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MyArticles', to=settings.AUTH_USER_MODEL),
        ),
    ]
