# Generated by Django 4.0.4 on 2022-07-09 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NewsArchive', '0013_remove_article_source_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MyArticles', to=settings.AUTH_USER_MODEL),
        ),
    ]
