# Generated by Django 4.0.4 on 2022-07-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsArchive', '0015_alter_configuration_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
