# Generated by Django 4.0.4 on 2022-07-10 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsArchive', '0017_article_publishedstr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publishedStr',
            new_name='aggregatedDate',
        ),
    ]
