# Generated by Django 4.0.4 on 2022-07-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsArchive', '0021_alter_article_article_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='aggregatedYear',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
