# Generated by Django 4.0.4 on 2022-07-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsArchive', '0022_alter_article_aggregatedyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='discription',
            field=models.TextField(default='No description'),
        ),
    ]
