# Generated by Django 4.0.4 on 2022-07-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsArchive', '0024_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='discription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
