# Generated by Django 4.0.4 on 2022-07-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsArchive', '0025_alter_article_discription_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image_url',
            field=models.URLField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_url',
            field=models.URLField(blank=True, max_length=450, null=True),
        ),
    ]
