# Generated by Django 4.0.4 on 2022-06-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('human', 'human'), ('identicon', 'identicon'), ('bottts', 'bottts'), ('jdenticon', 'jdenticon'), ('avataaars', 'avataaars'), ('gridy', 'gridy'), ('micah', 'micah')], default='identicon', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='seed',
            field=models.CharField(default='.5an4"(G-8', max_length=10),
        ),
    ]
