# Generated by Django 4.0.4 on 2022-06-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_gender_user_seed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='seed',
        ),
    ]
