# Generated by Django 4.0.4 on 2022-06-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_user_seed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gender',
            new_name='avatar',
        ),
        migrations.AlterField(
            model_name='user',
            name='seed',
            field=models.CharField(default='Yz"aJ2Qw=c', max_length=10),
        ),
    ]
