# Generated by Django 4.0.4 on 2022-06-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_rename_gender_user_avatar_alter_user_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='seed',
            field=models.CharField(default='1H)u`Y5LGN', max_length=10),
        ),
    ]
